/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package be.ac.vub.simplegt.resource.simplegt.grammar;

public class SimplegtGrammarInformationProvider {
	
	public final static org.eclipse.emf.ecore.EStructuralFeature ANONYMOUS_FEATURE = org.eclipse.emf.ecore.EcoreFactory.eINSTANCE.createEAttribute();
	static {
		ANONYMOUS_FEATURE.setName("_");
	}
	
	public static class Rule extends be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSyntaxElement {
		
		private final org.eclipse.emf.ecore.EClass metaclass;
		
		public Rule(org.eclipse.emf.ecore.EClass metaclass, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice choice, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality cardinality) {
			super(cardinality, new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSyntaxElement[] {choice});
			this.metaclass = metaclass;
		}
		
		public org.eclipse.emf.ecore.EClass getMetaclass() {
			return metaclass;
		}
		
		public be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice getDefinition() {
			return (be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice) getChildren()[0];
		}
	}
	
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_0_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword("module", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder SIMPLEGT_0_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getModule().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.MODULE__NAME), "TEXT", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_0_0_0_2 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword(";", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_0_0_0_3_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword("import", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder SIMPLEGT_0_0_0_3_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getModule().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.MODULE__IMPORTS), "TEXT", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_0_0_0_3_0_0_2 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword(";", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_0_0_0_3_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_0_0_0_3_0_0_0, SIMPLEGT_0_0_0_3_0_0_1, SIMPLEGT_0_0_0_3_0_0_2);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_0_0_0_3_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_0_0_0_3_0_0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound SIMPLEGT_0_0_0_3 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound(SIMPLEGT_0_0_0_3_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.STAR);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_0_0_0_4 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword("transform", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment SIMPLEGT_0_0_0_5 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getModule().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.MODULE__MODELS), be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_0_0_0_6_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword(",", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment SIMPLEGT_0_0_0_6_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getModule().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.MODULE__MODELS), be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_0_0_0_6_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_0_0_0_6_0_0_0, SIMPLEGT_0_0_0_6_0_0_1);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_0_0_0_6_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_0_0_0_6_0_0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound SIMPLEGT_0_0_0_6 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound(SIMPLEGT_0_0_0_6_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.STAR);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_0_0_0_7 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword(";", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment SIMPLEGT_0_0_0_8 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getModule().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.MODULE__RULES), be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.STAR, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_0_0_0_0, SIMPLEGT_0_0_0_1, SIMPLEGT_0_0_0_2, SIMPLEGT_0_0_0_3, SIMPLEGT_0_0_0_4, SIMPLEGT_0_0_0_5, SIMPLEGT_0_0_0_6, SIMPLEGT_0_0_0_7, SIMPLEGT_0_0_0_8);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_0_0_0);
	public final static Rule SIMPLEGT_0 = new Rule(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getModule(), SIMPLEGT_0_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder SIMPLEGT_1_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getInstanceModel().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.INSTANCE_MODEL__NAME), "TEXT", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_1_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword(":", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment SIMPLEGT_1_0_0_2 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getInstanceModel().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.INSTANCE_MODEL__META_MODEL), be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_1_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_1_0_0_0, SIMPLEGT_1_0_0_1, SIMPLEGT_1_0_0_2);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_1_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_1_0_0);
	public final static Rule SIMPLEGT_1 = new Rule(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getInstanceModel(), SIMPLEGT_1_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder SIMPLEGT_2_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getMetamodel().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.METAMODEL__NAME), "TEXT", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_2_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_2_0_0_0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_2_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_2_0_0);
	public final static Rule SIMPLEGT_2 = new Rule(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getMetamodel(), SIMPLEGT_2_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtBooleanTerminal SIMPLEGT_3_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtBooleanTerminal(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getRule().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.RULE__ABSTRACT), "abstract", "", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_3_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword("rule", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder SIMPLEGT_3_0_0_2 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getRule().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.RULE__NAME), "TEXT", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_3_0_0_3_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword("extends", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder SIMPLEGT_3_0_0_3_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getRule().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.RULE__EXTENDS), "TEXT", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_3_0_0_3_0_0_2_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword(",", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder SIMPLEGT_3_0_0_3_0_0_2_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getRule().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.RULE__EXTENDS), "TEXT", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_3_0_0_3_0_0_2_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_3_0_0_3_0_0_2_0_0_0, SIMPLEGT_3_0_0_3_0_0_2_0_0_1);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_3_0_0_3_0_0_2_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_3_0_0_3_0_0_2_0_0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound SIMPLEGT_3_0_0_3_0_0_2 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound(SIMPLEGT_3_0_0_3_0_0_2_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.STAR);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_3_0_0_3_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_3_0_0_3_0_0_0, SIMPLEGT_3_0_0_3_0_0_1, SIMPLEGT_3_0_0_3_0_0_2);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_3_0_0_3_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_3_0_0_3_0_0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound SIMPLEGT_3_0_0_3 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound(SIMPLEGT_3_0_0_3_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.QUESTIONMARK);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_3_0_0_4 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword("{", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment SIMPLEGT_3_0_0_5 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getRule().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.RULE__INPUT), be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.QUESTIONMARK, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment SIMPLEGT_3_0_0_6 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getRule().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.RULE__NAC), be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.STAR, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment SIMPLEGT_3_0_0_7 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getRule().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.RULE__OUTPUT), be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.QUESTIONMARK, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_3_0_0_8 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword("}", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_3_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_3_0_0_0, SIMPLEGT_3_0_0_1, SIMPLEGT_3_0_0_2, SIMPLEGT_3_0_0_3, SIMPLEGT_3_0_0_4, SIMPLEGT_3_0_0_5, SIMPLEGT_3_0_0_6, SIMPLEGT_3_0_0_7, SIMPLEGT_3_0_0_8);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_3_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_3_0_0);
	public final static Rule SIMPLEGT_3 = new Rule(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getRule(), SIMPLEGT_3_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_4_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword("from", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment SIMPLEGT_4_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getInPattern().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.IN_PATTERN__ELEMENTS), be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_4_0_0_2_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword(",", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment SIMPLEGT_4_0_0_2_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getInPattern().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.IN_PATTERN__ELEMENTS), be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_4_0_0_2_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_4_0_0_2_0_0_0, SIMPLEGT_4_0_0_2_0_0_1);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_4_0_0_2_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_4_0_0_2_0_0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound SIMPLEGT_4_0_0_2 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound(SIMPLEGT_4_0_0_2_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.STAR);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_4_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_4_0_0_0, SIMPLEGT_4_0_0_1, SIMPLEGT_4_0_0_2);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_4_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_4_0_0);
	public final static Rule SIMPLEGT_4 = new Rule(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getInPattern(), SIMPLEGT_4_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder SIMPLEGT_5_0_0_0_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getType().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.TYPE__MODEL), "TEXT", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_5_0_0_0_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword("!", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_5_0_0_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_5_0_0_0_0_0_0, SIMPLEGT_5_0_0_0_0_0_1);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_5_0_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_5_0_0_0_0_0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound SIMPLEGT_5_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound(SIMPLEGT_5_0_0_0_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.QUESTIONMARK);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder SIMPLEGT_5_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getType().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.TYPE__NAME), "TEXT", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_5_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_5_0_0_0, SIMPLEGT_5_0_0_1);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_5_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_5_0_0);
	public final static Rule SIMPLEGT_5 = new Rule(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getType(), SIMPLEGT_5_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder SIMPLEGT_6_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getInputElement().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.INPUT_ELEMENT__NAME), "TEXT", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_6_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword(":", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment SIMPLEGT_6_0_0_2 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getInputElement().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.INPUT_ELEMENT__TYPE), be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_6_0_0_3_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword("=", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment SIMPLEGT_6_0_0_3_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getInputElement().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.INPUT_ELEMENT__BINDING), be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_6_0_0_3_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_6_0_0_3_0_0_0, SIMPLEGT_6_0_0_3_0_0_1);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_6_0_0_3_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_6_0_0_3_0_0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound SIMPLEGT_6_0_0_3 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound(SIMPLEGT_6_0_0_3_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.QUESTIONMARK);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_6_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_6_0_0_0, SIMPLEGT_6_0_0_1, SIMPLEGT_6_0_0_2, SIMPLEGT_6_0_0_3);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_6_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_6_0_0);
	public final static Rule SIMPLEGT_6 = new Rule(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getInputElement(), SIMPLEGT_6_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder SIMPLEGT_7_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getInputBinding().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.INPUT_BINDING__ELEMENT), "TEXT", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_7_0_0_1_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword(".", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder SIMPLEGT_7_0_0_1_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getInputBinding().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.INPUT_BINDING__FEATURE), "TEXT", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_7_0_0_1_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_7_0_0_1_0_0_0, SIMPLEGT_7_0_0_1_0_0_1);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_7_0_0_1_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_7_0_0_1_0_0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound SIMPLEGT_7_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound(SIMPLEGT_7_0_0_1_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.QUESTIONMARK);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_7_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_7_0_0_0, SIMPLEGT_7_0_0_1);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_7_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_7_0_0);
	public final static Rule SIMPLEGT_7 = new Rule(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getInputBinding(), SIMPLEGT_7_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_8_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword("not", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment SIMPLEGT_8_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getNacPattern().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.NAC_PATTERN__ELEMENTS), be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_8_0_0_2_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword(",", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment SIMPLEGT_8_0_0_2_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getNacPattern().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.NAC_PATTERN__ELEMENTS), be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_8_0_0_2_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_8_0_0_2_0_0_0, SIMPLEGT_8_0_0_2_0_0_1);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_8_0_0_2_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_8_0_0_2_0_0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound SIMPLEGT_8_0_0_2 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound(SIMPLEGT_8_0_0_2_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.STAR);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_8_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_8_0_0_0, SIMPLEGT_8_0_0_1, SIMPLEGT_8_0_0_2);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_8_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_8_0_0);
	public final static Rule SIMPLEGT_8 = new Rule(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getNacPattern(), SIMPLEGT_8_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_9_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword("to", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment SIMPLEGT_9_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getOutPattern().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.OUT_PATTERN__ELEMENTS), be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_9_0_0_2_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword(",", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment SIMPLEGT_9_0_0_2_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getOutPattern().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.OUT_PATTERN__ELEMENTS), be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_9_0_0_2_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_9_0_0_2_0_0_0, SIMPLEGT_9_0_0_2_0_0_1);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_9_0_0_2_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_9_0_0_2_0_0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound SIMPLEGT_9_0_0_2 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound(SIMPLEGT_9_0_0_2_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.STAR);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_9_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_9_0_0_0, SIMPLEGT_9_0_0_1, SIMPLEGT_9_0_0_2);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_9_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_9_0_0);
	public final static Rule SIMPLEGT_9 = new Rule(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getOutPattern(), SIMPLEGT_9_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder SIMPLEGT_10_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getOutputElement().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.OUTPUT_ELEMENT__NAME), "TEXT", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_10_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword(":", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment SIMPLEGT_10_0_0_2 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getOutputElement().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.OUTPUT_ELEMENT__TYPE), be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_10_0_0_3_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword("(", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment SIMPLEGT_10_0_0_3_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getOutputElement().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.OUTPUT_ELEMENT__BINDINGS), be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_10_0_0_3_0_0_2_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword(",", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment SIMPLEGT_10_0_0_3_0_0_2_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtContainment(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getOutputElement().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.OUTPUT_ELEMENT__BINDINGS), be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_10_0_0_3_0_0_2_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_10_0_0_3_0_0_2_0_0_0, SIMPLEGT_10_0_0_3_0_0_2_0_0_1);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_10_0_0_3_0_0_2_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_10_0_0_3_0_0_2_0_0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound SIMPLEGT_10_0_0_3_0_0_2 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound(SIMPLEGT_10_0_0_3_0_0_2_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.STAR);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_10_0_0_3_0_0_3 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword(")", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_10_0_0_3_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_10_0_0_3_0_0_0, SIMPLEGT_10_0_0_3_0_0_1, SIMPLEGT_10_0_0_3_0_0_2, SIMPLEGT_10_0_0_3_0_0_3);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_10_0_0_3_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_10_0_0_3_0_0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound SIMPLEGT_10_0_0_3 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound(SIMPLEGT_10_0_0_3_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.QUESTIONMARK);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_10_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_10_0_0_0, SIMPLEGT_10_0_0_1, SIMPLEGT_10_0_0_2, SIMPLEGT_10_0_0_3);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_10_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_10_0_0);
	public final static Rule SIMPLEGT_10 = new Rule(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getOutputElement(), SIMPLEGT_10_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder SIMPLEGT_11_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getOutputBinding().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.OUTPUT_BINDING__TARGET_FEATURE), "TEXT", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_11_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword(":=", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder SIMPLEGT_11_0_0_2 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getOutputBinding().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.OUTPUT_BINDING__ELEMENT), "TEXT", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword SIMPLEGT_11_0_0_3_0_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtKeyword(".", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder SIMPLEGT_11_0_0_3_0_0_1 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtPlaceholder(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getOutputBinding().getEStructuralFeature(be.ac.vub.simplegt.SimplegtPackage.OUTPUT_BINDING__FEATURE), "TEXT", be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, 0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_11_0_0_3_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_11_0_0_3_0_0_0, SIMPLEGT_11_0_0_3_0_0_1);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_11_0_0_3_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_11_0_0_3_0_0);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound SIMPLEGT_11_0_0_3 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCompound(SIMPLEGT_11_0_0_3_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.QUESTIONMARK);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence SIMPLEGT_11_0_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtSequence(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_11_0_0_0, SIMPLEGT_11_0_0_1, SIMPLEGT_11_0_0_2, SIMPLEGT_11_0_0_3);
	public final static be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice SIMPLEGT_11_0 = new be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtChoice(be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE, SIMPLEGT_11_0_0);
	public final static Rule SIMPLEGT_11 = new Rule(be.ac.vub.simplegt.SimplegtPackage.eINSTANCE.getOutputBinding(), SIMPLEGT_11_0, be.ac.vub.simplegt.resource.simplegt.grammar.SimplegtCardinality.ONE);
}
